
# Tasks for Installing Neutron for Ubuntu
- name: Install Neutron Packages
  apt:
    name:
     - neutron-server
     - neutron-plugin-ml2
     - neutron-linuxbridge-agent
     - neutron-l3-agent
     - neutron-dhcp-agent
     - neutron-metadata-agent
    state: present
  when: ansible_distribution == "Ubuntu"

# Tasks to Configure Neutron for Ubuntu 
- name: Configure the Installed Neutron
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  when: ansible_distribution == "Ubuntu"

- name: Configure ML2 Plugin
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  when: ansible_distribution == "Ubuntu"

- name: Restart Neutron Service
  service:
    name: neutron-server
    state: restarted
  when: ansible_distribution == "Ubuntu"
