
# Tasks to Install Horizon for Ubuntu
- name: Install Horizon packages
  apt:
    name:
     - openstack-dashboard
    state: present
  when: ansible_distribution == "Ubuntu"

# Configuring the Installed Horizon Service
- name: Configure Apache for Horizon
  template:
    src: openstack-dashboard.conf.j2
    dest: /etc/apache2/sites-available/openstack-dashboard.conf
  when: ansible_distribution == "Ubuntu"

- name: Configure Horizon settings
  template:
    src: local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py
  when: ansible_distribution == "Ubuntu"

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu"
